Repository MITS-Felucca/Felucca, pull requests merged in 2020-05, with the labels that each got.

#99 add sample output
  test/sample_output/Readme.txt
  test/sample_output/facts
  test/sample_output/output.json
  test/sample_output/results
Labels: development

#102 set up infra and unit test
  .gitignore
  felucca/.gitkeep
  felucca/__init__.py
  felucca/backend/__init__.py
  felucca/backend/execution_manager.py
  felucca/backend/job_manager.py
  felucca/backend/resource_manager.py
  felucca/backend/server.py
  felucca/common/__init__.py
  felucca/common/job.py
  felucca/common/task.py
  felucca/config.py
  tests/sample_output/Readme.txt
  tests/sample_output/facts
  tests/sample_output/output.json
  tests/sample_output/results
  tests/unit_test/common/job_test.py
  tests/unit_test/common/output.json
  tests/unit_test/common/pharos.log
  tests/unit_test/common/task_test.py
Labels: development

#105 fix task_ids and add stderr
  felucca/backend/common/__init__.py
  felucca/backend/common/job.py
  felucca/backend/common/task.py
  tests/unit_test/backend/common/job_test.py
  tests/unit_test/backend/common/output.json
  tests/unit_test/backend/common/pharos.log
  tests/unit_test/backend/common/task_test.py
Labels: bug

#104 implement container server run functionality and sending back output,…
  .gitignore
  env/docker/DockerFile
  env/docker/container_server.py
  env/docker/microserver.py
  env/docker/oo.exe
  env/docker/test_server.py
  felucca/backend/container_server.py
  tests/unit_test/container_server/test_server.py
Labels: Container Server, development

#115 Add enum Status
  env/docker/container_server.py
  felucca/backend/common/status.py
  felucca/backend/container_server.py
Labels: development

#118 Add Status in Task & Job
  felucca/backend/common/job.py
  felucca/backend/common/task.py
Labels: development

#119 fix status and import format
  env/docker/container_server.py
  felucca/backend/container_server.py
Labels: Container Server, development
